[package]
name = "tane-game-launcher"
version = "0.1.5"
edition = "2021"
workspace = "../.."

[dependencies]
tane-game = { package = "tane-game", path = "../.." }
bevy = "0.8"
image = "0.24.3"
winit = "0.26.1"
